var group___r_e_n_e_s_a_s___i_n_t_e_r_f_a_c_e_s =
[
    [ "ADC Interface", "group___a_d_c___a_p_i.html", "group___a_d_c___a_p_i" ],
    [ "CAN Interface", "group___c_a_n___a_p_i.html", "group___c_a_n___a_p_i" ],
    [ "Camera Interface", "group___c_a_m_e_r_a___a_p_i.html", "group___c_a_m_e_r_a___a_p_i" ],
    [ "Display Interface", "group___d_i_s_p_l_a_y___a_p_i.html", "group___d_i_s_p_l_a_y___a_p_i" ],
    [ "Ethernet Interface", "group___e_t_h_e_r___a_p_i.html", "group___e_t_h_e_r___a_p_i" ],
    [ "Ethernet PHY Interface", "group___e_t_h_e_r___p_h_y___a_p_i.html", "group___e_t_h_e_r___p_h_y___a_p_i" ],
    [ "External IRQ Interface", "group___e_x_t_e_r_n_a_l___i_r_q___a_p_i.html", "group___e_x_t_e_r_n_a_l___i_r_q___a_p_i" ],
    [ "I2C Master Interface", "group___i2_c___m_a_s_t_e_r___a_p_i.html", "group___i2_c___m_a_s_t_e_r___a_p_i" ],
    [ "I2C Slave Interface", "group___i2_c___s_l_a_v_e___a_p_i.html", "group___i2_c___s_l_a_v_e___a_p_i" ],
    [ "I2S Interface", "group___i2_s___a_p_i.html", "group___i2_s___a_p_i" ],
    [ "I/O Port Interface", "group___i_o_p_o_r_t___a_p_i.html", "group___i_o_p_o_r_t___a_p_i" ],
    [ "Image Scaling Interface", "group___i_m_a_g_e___s_c_a_l_i_n_g___a_p_i.html", "group___i_m_a_g_e___s_c_a_l_i_n_g___a_p_i" ],
    [ "Memory Managing Unit Interface", "group___m_m_u___a_p_i.html", "group___m_m_u___a_p_i" ],
    [ "SD/MMC Interface", "group___s_d_m_m_c___a_p_i.html", "group___s_d_m_m_c___a_p_i" ],
    [ "SPI Interface", "group___s_p_i___a_p_i.html", "group___s_p_i___a_p_i" ],
    [ "SPI Flash Interface", "group___s_p_i___f_l_a_s_h___a_p_i.html", "group___s_p_i___f_l_a_s_h___a_p_i" ],
    [ "Timer Interface", "group___t_i_m_e_r___a_p_i.html", "group___t_i_m_e_r___a_p_i" ],
    [ "Transfer Interface", "group___t_r_a_n_s_f_e_r___a_p_i.html", "group___t_r_a_n_s_f_e_r___a_p_i" ],
    [ "UART Interface", "group___u_a_r_t___a_p_i.html", "group___u_a_r_t___a_p_i" ],
    [ "USB Interface", "group___u_s_b___a_p_i.html", "group___u_s_b___a_p_i" ],
    [ "USB HHID Interface", "group___u_s_b___h_h_i_d___a_p_i.html", "group___u_s_b___h_h_i_d___a_p_i" ],
    [ "USB HMSC Interface", "group___u_s_b___h_m_s_c___a_p_i.html", "group___u_s_b___h_m_s_c___a_p_i" ],
    [ "USB PCDC Interface", "group___u_s_b___p_c_d_c___a_p_i.html", "group___u_s_b___p_c_d_c___a_p_i" ],
    [ "WDT Interface", "group___w_d_t___a_p_i.html", "group___w_d_t___a_p_i" ],
    [ "Block Media Interface", "group___r_m___b_l_o_c_k___m_e_d_i_a___a_p_i.html", "group___r_m___b_l_o_c_k___m_e_d_i_a___a_p_i" ],
    [ "FileX Block Media Port Interface", "group___r_m___f_i_l_e_x___b_l_o_c_k___m_e_d_i_a___a_p_i.html", "group___r_m___f_i_l_e_x___b_l_o_c_k___m_e_d_i_a___a_p_i" ],
    [ "FreeRTOS+FAT Port Interface", "group___r_m___f_r_e_e_r_t_o_s___p_l_u_s___f_a_t___a_p_i.html", "group___r_m___f_r_e_e_r_t_o_s___p_l_u_s___f_a_t___a_p_i" ]
];